### ISSUE TITLE
Search issues

### ISSUE THREAD

**Issue by flaneuse** [sebotic/repurpos.us#119]
## Structure searches with long SMILES:
- No results on [similarity search](https://reframedb.org/#/search?query=%5BH%5DC(C)(CC)%5BC@@%5D1(%5BH%5D)O%5BC@%5D2(CC%5BC@@H%5D1C)CC1C%5BC@@%5D(%5BH%5D)(C%5CC%3DC(C)%5C%5BC@@H%5D(O%5BC@@%5D3(%5BH%5D)C%5BC@H%5D(OC)%5BC@@H%5D(O%5BC@@%5D4(%5BH%5D)C%5BC@H%5D(OC)%5BC@@H%5D(O)%5BC@H%5D(C)O4)%5BC@H%5D(C)O3)%5BC@@H%5D(C)%5CC%3DC%5CC%3DC3%2FCO%5BC@%5D4(%5BH%5D)%5BC@H%5D(O)C(C)%3DC%5BC@@%5D(%5BH%5D)(C(%3DO)O1)%5BC@%5D34O)O2%20%7Cr,c:20,53,62,t:51%7C&type=structure&mode=similarity&tanimoto=0.85) but [stereofree](https://reframedb.org/#/search?query=%5BH%5DC(C)(CC)%5BC@@%5D1(%5BH%5D)O%5BC@%5D2(CC%5BC@@H%5D1C)CC1C%5BC@@%5D(%5BH%5D)(C%5CC%3DC(C)%5C%5BC@@H%5D(O%5BC@@%5D3(%5BH%5D)C%5BC@H%5D(OC)%5BC@@H%5D(O%5BC@@%5D4(%5BH%5D)C%5BC@H%5D(OC)%5BC@@H%5D(O)%5BC@H%5D(C)O4)%5BC@H%5D(C)O3)%5BC@@H%5D(C)%5CC%3DC%5CC%3DC3%2FCO%5BC@%5D4(%5BH%5D)%5BC@H%5D(O)C(C)%3DC%5BC@@%5D(%5BH%5D)(C(%3DO)O1)%5BC@%5D34O)O2%20%7Cr,c:20,53,62,t:51%7C&type=structure&mode=stereofree) works
- Another example: https://reframedb.org/#/search?query=CC1%3DC(C%3DCC2%3DC1C(%3DNC(%3DN2)N)N)CNC3%3DCC(%3DC(C(%3DC3)OC)OC)OC&type=structure&mode=similarity&tanimoto=0.85
- More: exact (fails): https://reframedb.org/#/search?query=%5BK%2B%5D.CCOC(%3DO)C1%3DC(COCCN)NC(C)%3DC(C1c1ccccc1Cl)C(%3DO)OC.CCCCc1nc(Cl)c(CO)n1Cc1ccc(cc1)-c1ccccc1-c1nn%5Bn-%5Dn1&type=structure&mode=exact
similarity (fine): https://reframedb.org/#/search?query=%5BK%2B%5D.CCOC(%3DO)C1%3DC(COCCN)NC(C)%3DC(C1c1ccccc1Cl)C(%3DO)OC.CCCCc1nc(Cl)c(CO)n1Cc1ccc(cc1)-c1ccccc1-c1nn%5Bn-%5Dn1&type=structure&mode=exact

Also display better error message.

## Text searches
- Missing aliases in select search results?  See [paclitaxel](https://reframedb.org/#/search?query=paclitaxel&type=string) -- also Taxol isn't searchable as a result.

**Comment by flaneuse** [comment]
Searching for "QC-12" works, but not QC-12 (presumably due to elastic hyphen splitting) @sebotic

**Comment by sebotic** [comment]
all of these have been resolved
