### ISSUE TITLE
Search result lacks similar compounds

### ISSUE THREAD

**Issue by sebotic** [sebotic/repurpos.us#124]
It seems that under certain conditions, search results lack similar compounds on the frontend, although these are being returned by the backend.

Example:
execute the following search:
https://reframedb.org/#/search?query=CEFDALOXIME%20PENTEXIL&type=string

Last result lacks similar compounds.

Execute the same search with a direct API call, the similar compounds are there as expected.
search API result
https://reframedb.org/api/search?query=CEFDALOXIME%20PENTEXIL&type=string

**Comment by sebotic** [comment]
On the compounds page, the similar compounds seem to be displayed just fine, so this should only be a minor thing

**Comment by flaneuse** [comment]
@sebotic no similar compounds are returned if the compound is in the Reframe library. My understanding of Calibr's desired functionality was that "similar compounds" in the search results was only intended to show similar *reframe* compounds, not all compounds, and only if it wasn't in the library.  If this is still the ideal behavior, the backend needs to filter out the non-Reframe similar compounds.

@andrewsu @sebotic what do we want the behavior to be?
1. Red dot if in RFM collection, show similar *RFM* compounds if not.
2. Red/white dot if in RFM collection, show *all* similar compounds, regardless if the compound itself is in the library
