### ISSUE TITLE
Substructure search issues

### ISSUE THREAD

**Issue by flaneuse** [sebotic/repurpos.us#137]
| query | expected molecule | observed  |
|---|---|---|
| http://reframedb.org/#/search?query=CS(%3DO)(%3DO)C1C%3DCC%3DCC%3D1&type=substructure | Empesertib | no results |
| O=COc1ccccc1O[H] | QC-12 | no results |
| CB(O)O | maybe: all borates (?) | only aliphatic ones |
| 'cB(O)O' or '[#6]B(O)O' | aromatic borates | aromatic borates |
| O=N+[O-] | any nitrobenzene | no results |
| c1ccccc1N(=O)=O |  ~ 150 results, e.g. Licostinel and HE-30582 | 3 results |
| c1ccccc1[N+](=O)[O-] |  ~ 150 results, e.g.  Licostinel and HE-30582 | no results |

**Comment by jeffjanes** [comment]
Looks like some of the examples are being eaten by markdown, by conversion to footnotes/links.  Closing square followed by a opening round is special, looks like you can escape them by backwhacking any of the 4 involved brackets.

 
O=\[N+](C1=CC=CC=C1)[O-]

c1ccccc1\[N+](=O)[O-]

The use of octothorpe to cross-reference issue numbers seems to unescapable, however.

Ah, good times.  I can't wait until we need to markdown a regular expression which needs to be passed through a shell script to convert a SMILES into a SMARTS while changing the cis-trans stereochemistry of every other double bond.
