### ISSUE TITLE
fix search issues

### ISSUE THREAD

**Issue by andrewsu** [sebotic/repurpos.us#15]
Currently searching "acet" does _not_ return acetaminophen (it should), while searching "aceta" works as expected.  Similarly, "tr', "tri", "trim", "trime", and "trimet" don't return trimetrexate.

related to #12

**Comment by flaneuse** [comment]
+ compounds without a Wikidata ID are unsearchable (e.g. "Decamethoxine = ZADGGFKUEYIBJC-UHFFFAOYSA-N", "ZVYVPGLRVWUPMP-UHFFFAOYSA-N").  @sebotic convert unique IDs / queries to reframe IDs?
