### ISSUE TITLE
similarity search broken?

### ISSUE THREAD

**Issue by andrewsu** [sebotic/repurpos.us#150]
https://reframedb.org/search?query=Cc1nc(sc1COc1ccc(c(c1)Cl)C(%3DO)O)c1ccc(cc1)C(F)(F)F&type=structure&mode=similarity&tanimoto=0.85

This search returns no results (at any tanimoto threshold), but this structure is an exact match to a reframe compound as retrieved by this search:

https://reframedb.org/search?query=Cc1nc(sc1COc1ccc(c(c1)Cl)C(%3DO)O)c1ccc(cc1)C(F)(F)F&type=structure&mode=exact

similar results directly on the API:

https://reframedb.org/api/search?query=Cc1nc(sc1COc1ccc(c(c1)Cl)C(%253DO)O)c1ccc(cc1)C(F)(F)F&type=structure&tanimoto=0.85&mode=similarity (zero hits)
https://reframedb.org/api/search?query=Cc1nc(sc1COc1ccc(c(c1)Cl)C(%253DO)O)c1ccc(cc1)C(F)(F)F&type=structure&mode=exact (one hit)

**Comment by flaneuse** [comment]
Similarity search @ threshold of <= 0.5 works, FYI.

https://reframedb.org/search?query=Cc1nc(sc1COc1ccc(c(c1)Cl)C(%3DO)O)c1ccc(cc1)C(F)(F)F&type=structure&mode=similarity&tanimoto=0.5

**Comment by sebotic** [comment]
This one should be resolved
