### ISSUE TITLE
On compound details page, add vendor annotation data when no wikidata annotations exist

### ISSUE THREAD

**Issue by andrewsu** [sebotic/repurpos.us#36]
Currently, there are several fields (including compound names and aliases) from the vendor annotations that are _not_ shown on the compound details page, primarily because they are redundant with information that is drawn from Wikidata.  

We need to adjust this so that _all_ annotation data from the vendors is shown.  A first-pass solution is to simply have data duplicated in several sections of the page.  A smarter solution would be to only show names/aliases in the vendor sections that are _not_ also available from wikidata.

**Comment by flaneuse** [comment]
closed w/ PR #40
