### ISSUE TITLE
Optimize app loading time

### ISSUE THREAD

**Issue by sebotic** [sebotic/repurpos.us#49]
The app does not seem to load particularly fast. One reason could be that a few JavaScript/styling libraries are loaded from CDNs. Check perfromance and integrate these libraries with the app package, so everything will be loaded from our server.

**Comment by andrewsu** [comment]
per @tljesse's comment on PR #50, do we still need to enable AoT and gzip compression?

**Comment by tljesse** [comment]
AoT is done during the build, gzip is all that needs to be enabled on the server. [Lines 12-15](https://github.com/sebotic/repurpos.us/blob/master/package.json#L12-L15) in package.json show how the build is done.

**Comment by sebotic** [comment]
that's now fast enough
