### ISSUE TITLE
Weird search behavior

### ISSUE THREAD

**Issue by flaneuse** [sebotic/repurpos.us#60]
- [XUEXKLQUXRIRAG-UHFFFAOYSA-N, FPLIKVAYWLYPAO-LBPRGKRZSA-N, OLNJLTFSGFZCKE-UHFFFAOYSA-N, others] --> no main_labels in search / on compound page
- "imatinib mesylate" doesn't return imatinib, but does return a lot of other stuff-- is that expected?
- Do we want to support "" --> exact text matching ?
- query=C1=CN=CN=C1N&type=structure&mode=similarity&tanimoto=0.85 doesn't return imatinib

**Comment by sebotic** [comment]
I have noticed the label issue as well, will have a look at it.

search for imatinib mesylate has imatinib mesylate as the first result

**Comment by flaneuse** [comment]
sorry, my sorting func was incorrect, i see imatinib now
