### ISSUE TITLE
split vendor annotation tables

### ISSUE THREAD

**Issue by andrewsu** [sebotic/repurpos.us#8]
As an example, when logged in this URL http://52.53.120.17:34568/#/compound_data/Q18216 renders like this:

![2018-02-22_10-28-08](https://user-images.githubusercontent.com/2635409/36556758-1b91db42-17bb-11e8-9ca4-dc90f4e0ef61.jpg)

The annotation table combines data from the three different vendors (GVK BioSciences, Thomson Reuters, and Informa), referenced with footnotes.  We need to split out this combined table into three separate tables, each displaying information from a single vendor.

Despite the confusing API endpoint name, this service call (with auth headers) will return annotation data for all three vendors: http://52.53.120.17:5000/gvk_data?qid=Q18216

**Comment by sebotic** [comment]
that should be solved now, at least on the data side of things, one might want to work on presentation and styling
<img width="1084" alt="screen shot 2018-03-05 at 3 58 56 pm" src="https://user-images.githubusercontent.com/7053730/36981789-563a60c6-208e-11e8-9140-d80142ebb2fa.png">
